# Generated by Django 4.2.2 on 2024-04-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerId', models.IntegerField(unique=True)),
                ('status', models.BooleanField(default=False)),
                ('count', models.IntegerField(default=0)),
                ('upTime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('contestId', models.CharField(editable=False, max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('startTime', models.DateTimeField(blank=True)),
                ('endTime', models.DateTimeField(blank=True)),
                ('isStarted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DockerJudgeContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vm', models.IntegerField(default=0)),
                ('maxNumber', models.IntegerField(default=10)),
            ],
        ),
        migrations.CreateModel(
            name='ActivatedContainer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerId', models.CharField(max_length=150)),
                ('disable', models.BooleanField(default=False)),
                ('upTime', models.DateTimeField(auto_now=True)),
                ('vm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.dockerjudgecontainer')),
            ],
        ),
    ]
