# Generated by Django 4.2.2 on 2024-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registrationOpen',
            field=models.BooleanField(default=True),
        ),
    ]
