version: '3'

services:
# used doc : https://medium.com/@adamsokode/dockerize-django-application-with-nginx-reverse-proxy-79036606fa5
  nginx:
    build: ./nginx
    volumes:
      - ./static:/home/app/static
    ports:
      - "80:80"
      # - "443:443"
    depends_on:
      - web
    restart: "on-failure"
  
  web:
    build: . #build the image for the web service from the dockerfile in parent directory
    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py run_celery_task &&
                    python manage.py collectstatic --no-input &&
                    gunicorn NCC.wsgi:application --bind 0.0.0.0:8000 -w 3 --max-requests 300"
    volumes:
      - .:/home/app # map data and files from parent directory in host to microservice directory in docker containers
      - /var/run/docker.sock:/var/run/docker.sock
      # - /usr/bin/docker:/usr/bin/docker
      - ./static:/home/app/static
    env_file:
      - .env
  # worker:
  #   restart: unless-stopped
  #   build: .
  #   # command: sh -c "celery -A NCC worker --loglevel=info --concurrency 3 -E"
  #   command: sh -c "celery -A NCC worker --loglevel=info --concurrency 3 -E "
  #   volumes:
  #       - .:/home/app
  #       - /var/run/docker.sock:/var/run/docker.sock
  #       - ./static:/home/app/static
  #   env_file:
  #     - .env

  redis:
    restart: unless-stopped
    image: redis:7.0.5-alpine 
    expose:
        - 6379

        
volumes:
  static_volume:
  postgres_data:


