# Generated by Django 4.2.2 on 2024-07-16 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='constraints',
        ),
        migrations.RemoveField(
            model_name='question',
            name='inputOutputBlock',
        ),
        migrations.RemoveField(
            model_name='question',
            name='ipFormate',
        ),
        migrations.RemoveField(
            model_name='question',
            name='opFormate',
        ),
    ]
