# Generated by Django 4.2.2 on 2024-08-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_submission_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('WA', 'Wrong Answer'), ('AC', 'Accepted'), ('PEN', 'Pending'), ('ONF', 'Output Not Found'), ('UE', 'Unknown Error')], max_length=5, null=True),
        ),
    ]
