# Generated by Django 4.2.2 on 2024-08-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_submission_submissionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestcaseForQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=10, unique=True)),
                ('isFetched', models.BooleanField(default=False)),
            ],
        ),
    ]
