# Generated by Django 4.2.2 on 2024-08-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_testcaseforquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcaseforquestion',
            name='contest',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
