# Generated by Django 4.2.2 on 2024-10-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_testcaseforquestion_contest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='mode',
            field=models.CharField(blank=True, choices=[('RUN', 'Run Submission'), ('SUB', 'Submit Submission'), ('RC', 'RC Submission')], max_length=5, null=True),
        ),
    ]
