# Generated by Django 4.2.2 on 2024-04-15 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('question', '0001_initial'),
        ('contest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('python', 'python'), ('cpp', 'cpp'), ('c', 'c'), ('java', 'java')], max_length=10)),
                ('code', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(default=0)),
                ('attemptedNumber', models.IntegerField(default=0)),
                ('submissionTime', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('WA', 'Wrong Answer'), ('AC', 'Accepted'), ('PEN', 'Pending'), ('ONF', 'Output Not Found')], max_length=5, null=True)),
                ('isCorrect', models.BooleanField(default=False)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contest.contest')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.team')),
            ],
        ),
        migrations.CreateModel(
            name='CorrectCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_code', models.TextField()),
                ('language', models.CharField(choices=[('python', 'python'), ('cpp', 'cpp'), ('c', 'c'), ('java', 'java')], max_length=10)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
    ]
