# Generated by Django 4.2.2 on 2024-07-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='correctSubmissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='totalSubmissions',
            field=models.IntegerField(default=0),
        ),
    ]
