# Generated by Django 4.2.2 on 2024-08-09 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0002_submission_correctsubmissions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='input',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='output',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(blank=True, choices=[('TLE', 'Time Limit Exceeded'), ('MLE', 'Memory Limit Exceeded'), ('CE', 'Compilation Error'), ('RE', 'Runtime Error'), ('WA', 'Wrong Answer'), ('AC', 'Accepted'), ('PEN', 'Pending'), ('ONF', 'Output Not Found'), ('UE', 'Unknown Error')], max_length=5, null=True),
        ),
    ]
