# Generated by Django 4.2.2 on 2024-08-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0003_submission_error_submission_input_submission_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='mode',
            field=models.CharField(blank=True, choices=[('RUN', 'Run Submission'), ('SUB', 'Submit Submission')], max_length=5, null=True),
        ),
    ]
